module pll (
    input i_clk,
    output o_clk,
    output o_lock
);
    // Generated by icepll -i 12 -o 20

    // F_PLLIN:    12.000 MHz (given)
    // F_PLLOUT:   40.000 MHz (requested)
    // F_PLLOUT:   39.750 MHz (achieved)

    // FEEDBACK: SIMPLE
    // F_PFD:   12.000 MHz
    // F_VCO:  636.000 MHz

    // DIVR:  0 (4'b0000)
    // DIVF: 52 (7'b0110100)
    // DIVQ:  5 (3'b100)

    // FILTER_RANGE: 1 (3'b001)

    // Phase locked loop
    SB_PLL40_2_PAD #(
    .FEEDBACK_PATH("SIMPLE"),
    .DIVR(4'b0000),
    .DIVF(7'b0110100),
    .DIVQ(3'b100),
    .FILTER_RANGE(3'b001)
    ) SB_PLL40_PAD_inst (
        .LOCK(o_lock),
        .RESETB(1'b1),
        .BYPASS(1'b0),
        .PACKAGEPIN(i_clk),
        .PLLOUTGLOBALA(o_clk)
    );

endmodule
