#!/bin/sh

lz4 -f -12 -B4 mecrisp-quintus-mch2022.bin mecrisp-quintus-mch2022.lz4
python3 rawlz4.py mecrisp-quintus-mch2022.lz4 mecrisp-quintus-mch2022.lz4.raw

riscv64-linux-gnu-as playground-decompressor.s -o playground-decompressor.o -march=rv32im
riscv64-linux-gnu-ld -o playground-decompressor.elf -T memmap playground-decompressor.o -m elf32lriscv
riscv64-linux-gnu-objdump -Mnumeric -D playground-decompressor.elf > playground-decompressor.list
riscv64-linux-gnu-objcopy playground-decompressor.elf playground-decompressor.bin -O binary

dd if=playground-decompressor.bin bs=1 count=10240 of=bootarea.bin
dd if=playground-decompressor.bin bs=1  skip=10240 of=textarea.bin

fpc -XX -Os binarytoverilog
./binarytoverilog bootarea.bin bootarea.hex

xxd --plain -c1 textarea.bin textarea.hex
