# Project config
PROJ := fading-rgb

PROJ_DEPS :=
PROJ_RTL_SRCS := $(addprefix rtl/, \
	breathe.v \
)
PROJ_TOP_SRC := rtl/fading_rgb.v
PROJ_TOP_MOD := top

# Include default rules
include ../_common/build.mk
